# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('algorithm_id', models.AutoField(primary_key=True, serialize=False)),
                ('algorithm_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('number_of_ps', models.IntegerField()),
                ('number_of_worker', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('time', models.FloatField()),
                ('algorithm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Algorithm')),
                ('ps_cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps_cluster_id', to='performance.Cluster')),
                ('worker_cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_cluster_id', to='performance.Cluster')),
            ],
        ),
    ]
